{% set name = "aiohttp" %}
{% set version = "3.8.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/aiohttp-{{ version }}.tar.gz
  sha256: 3828fb41b7203176b82fe5d699e0d845435f2374750a44b480ea6b930f6be269

build:
  skip: true  # [py<36]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython
    - setuptools
    - wheel
  run:
    - python
    - attrs >=17.3.0
    - charset-normalizer >=2.0,<3.0
    - multidict >=4.5,<7.0
    - async-timeout >=4.0.0a3,<5.0
    - asynctest ==0.13.0  # [py<38]
    - yarl >=1.0,<2.0
    - idna_ssl >=1.0  # [py<37]
    - typing-extensions >=3.7.4  # [py<38]
    - frozenlist >=1.1.1
    - aiosignal >=1.1.2

test:
  imports:
    - aiohttp
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/aio-libs/aiohttp
  license: Apache-2.0
  license_file: LICENSE.txt
  license_family: Apache
  summary: Async http client/server framework (asyncio)
  description: Async http client/server framework (asyncio)
  doc_url: https://docs.aiohttp.org/
  dev_url: https://github.com/aio-libs/aiohttp
  doc_source_url: https://github.com/aio-libs/aiohttp/tree/master/docs

extra:
  recipe-maintainers:
    - sodre
    - xhochy
    - ocefpaf
