{% set name = "aiohttp" %}
{% set version = "3.7.4.post0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 493d3299ebe5f5a7c66b9819eacdcfbbaaf1a8e84911ddffcdc48888497afecf

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<37]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython
  run:
    - python
    - async-timeout >=4.0a2,<5.0
    - asynctest ==0.13.0  # [py<38]
    #- attrs >=17.3.0
    - chardet >=2.0,<5.0
    - multidict >=4.5,<7.0
    - typing-extensions >=3.7.4
    - yarl >=1.0,<2
    - frozenlist >=1.1.1
    - aiosignal >=1.1.2

test:
  imports:
    - aiohttp
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/aio-libs/aiohttp
  license: Apache-2.0
  license_file: LICENSE.txt
  license_family: Apache
  summary: Async http client/server framework (asyncio)

  doc_url: http://aiohttp.readthedocs.io/
  dev_url: https://github.com/aio-libs/aiohttp
  doc_source_url: https://github.com/aio-libs/aiohttp/tree/master/docs

extra:
  recipe-maintainers:
    - sodre
    - xhochy
    - ocefpaf
