{% set name = "aiohttp" %}
{% set version = "3.8.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/aiohttp-{{ version }}.tar.gz
  sha256: b9552ec52cc147dbf1944ac7ac98af7602e51ea2dcd076ed194ca3c0d1c7d0bc

build:
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython
    - setuptools
    - wheel
  run:
    - python
    - multidict >=4.5,<7.0
    - async-timeout >=4.0,<5.0  # [py<311]
    - yarl >=1.0,<2.0
    - frozenlist >=1.1.1
    - aiosignal >=1.1.2

test:
  imports:
    - aiohttp
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/aio-libs/aiohttp
  license: Apache-2.0
  license_file: LICENSE.txt
  license_family: Apache
  summary: Async http client/server framework (asyncio)
  description: Async http client/server framework (asyncio)
  doc_url: https://docs.aiohttp.org/
  dev_url: https://github.com/aio-libs/aiohttp
  doc_source_url: https://github.com/aio-libs/aiohttp/tree/master/docs

extra:
  recipe-maintainers:
    - sodre
    - xhochy
    - ocefpaf
