{% set name = "aiohttp" %}
{% set version = "3.10.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/aiohttp-{{ version }}.tar.gz
  sha256: 9dc2b8f3dcab2e39e0fa309c8da50c3b55e6f34ab25f1a71d3288f24924d33a7

build:
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython
    - setuptools
    - wheel
  run:
    - python
    - aiohappyeyeballs >=2.3.0
    - aiosignal >=1.1.2
    - async-timeout >=4.0,<6.0  # [py<311]
    - attrs >=17.3.0
    - frozenlist >=1.1.1
    - multidict >=4.5,<7.0
    - yarl >=1.12.0,<2.0
  run_constrained:
    - aiodns >=3.2.0  # [not win]

test:
  imports:
    - aiohttp
  source_files:
    - tests
    - setup.cfg
    # used by a test
    - README.rst
  requires:
    - pip
    - pytest <8
    # flags '--cov=aiohttp --cov=tests/' are hardcoded in setup.cfg
    - pytest-cov
    - pytest-mock
    - pytest-xdist
    - pytest-codspeed
    - trustme
    - gunicorn  # [not (win or s390x)]
    - uvloop    # [not win]
    - brotli-python
    - re-assert
    - freezegun
  commands:
    - pip check
    # don't want the docker tests in the autobahn subfolder
    - rm -rf tests/autobahn         # [unix]
    - rmdir /s /q tests\autobahn    # [win]

    {% set tests_to_skip = "_not_a_real_test" %}
    # would requires package time-machine
    {% set tests_to_skip = tests_to_skip + " or test_expires or test_max_age or test_cookie_jar_clear_expired" %}
    # not sure why, they do appear in that issue: https://github.com/aio-libs/aiohttp/issues/7675
    {% set tests_to_skip = tests_to_skip + " or test_http_response_parser_bad_chunked_strict_c[pyloop]" %}
    {% set tests_to_skip = tests_to_skip + " or test_http_response_parser_bad_chunked_strict_py[pyloop]" %}
    {% set tests_to_skip = tests_to_skip + " or test_http_response_parser_strict_headers[c-parser-pyloop]" %}
    {% set tests_to_skip = tests_to_skip + " or test_access_root_of_static_handler[pyloop-index_forbidden]" %}
    {% set tests_to_skip = tests_to_skip + " or test_client_session_timeout_zero" %}
    # OSError regarding socket assigment
    {% set tests_to_skip = tests_to_skip + " or test_run_app_preexisting_inet6_socket[pyloop] " %}
    {% set tests_to_skip = tests_to_skip + " or test_handler_cancellation" %}
    {% set tests_to_skip = tests_to_skip + " or test_no_handler_cancellation" %}
    {% set tests_to_skip = tests_to_skip + " or test_shutdown_pending_handler_responds" %}
    {% set tests_to_skip = tests_to_skip + " or test_keepalive_timeout_sync_sleep or test_keepalive_timeout_async_sleep or test_HTTP_304[pyloop]" %}
    # CI is too slow for expected speed
    {% set tests_to_skip = tests_to_skip + " or test_import_time" %}  # [linux]
    # Permission errors on linux
    {% set tests_to_skip = tests_to_skip + " or test_test_server_hostnames[::1-::1] or test_send[request_start-params0-TraceRequestStartParams]" %}  # [linux]
    # Socket assisgnemnt errors on linux
    {% set tests_to_skip = tests_to_skip + " or test_static_directory_without_read_permission or test_static_file_without_read_permission" %}  # [linux]
    # windows - websocket ABNORMAL_CLOSURE
    {% set tests_to_skip = tests_to_skip + " or test_heartbeat[pyloop] or test_heartbeat_no_pong_after_receive_many_messages[pyloop] or test_normal_closure_while_client_sends_msg[pyloop]" %}  # [win]
    # PytestUnraisableExceptionWarning on s390x
    {% set tests_to_skip = tests_to_skip + " or test_release_early[pyloop]" %}
    # would requires package gunicorn
    {% set tests_to_skip = tests_to_skip + " or test_no_warnings[aiohttp.worker]" %} # [win or s390x]
    # ignore test files due to currently unavailable test dependencies (proxy.py)
    - pytest -k "not ({{ tests_to_skip }})" --ignore=tests/test_proxy_functional.py

about:
  home: https://github.com/aio-libs/aiohttp
  license: MIT AND Apache-2.0
  license_file:
    - LICENSE.txt
    - vendor/llhttp/LICENSE-MIT
  license_family: Other
  summary: Async http client/server framework (asyncio)
  description: Async http client/server framework (asyncio)
  doc_url: https://docs.aiohttp.org/
  dev_url: https://github.com/aio-libs/aiohttp

extra:
  recipe-maintainers:
    - sodre
    - xhochy
    - ocefpaf
