{% set name = "aiohttp" %}
{% set version = "3.1.3" %}
{% set sha256 = "9fcef0489e3335b200d31a9c1fb6ba80fdafe14cd82b971168c2f9fa1e4508ad" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  skip: true  # [py2k]

requirements:
  host:
    - python
    - setuptools
  run:
    - python
    - attrs >=17.3.0
    - chardet >=2.0,<4.0
    - multidict >=4.0,<5.0
    - async-timeout >=1.2,<3.0
    - yarl >=1.0,<2.0
    - idna_ssl >=1,<2  # [py35 or py36]

test:
  imports:
    - aiohttp

about:
  home: https://github.com/aio-libs/aiohttp
  license: Apache 2.0
  license_file: LICENSE.txt
  license_family: Apache
  summary: 'Async http client/server framework (asyncio)'

  doc_url: http://aiohttp.readthedocs.io/
  dev_url: https://github.com/aio-libs/aiohttp
  doc_source_url: https://github.com/aio-libs/aiohttp/tree/master/docs

extra:
  recipe-maintainers:
    - sodre
