travis:
  secure:
    BINSTAR_TOKEN: HpkOK1l9LXLKl/lxHiCTSYzECJhF7//dobYomh5fZ/0GXMZ6rwXZeMMpyHQYESpdD1IXiskY068K1oc2zlFaWNwJz0aUSkuOQPGYrsKP+VzwEHc6zcLzkynoZfWT3z6GN6diZnIfwJCUI9VOGZHLp1jpNm6knFf2v4R74F04f1LQt8oRtHHK6DWRMfUo/nOFLdTl5BnzE9zB4C2DEiLGT3Xgg0VFJrja14ADf/KeSibsLkD1VRywe+GUtLduzYK03ziZXHtX2E1Grpb/Ytxn5kKa1KQh7OBYpC6qWq+qlmWEPWbsOlYHfXJXNbLJ2mwjvy9mJoDk5sk/JHMP1TXCiFIm8uJ21WDdUw5QCLEFKX+hW8D7y/ny+HGHqivg3Q9+5ihq3jz65h9/oipCpulxXc1vzw6akZwZ6UV1HhbvpJG6RJLNS3dRuiGlMbfvFmFwI4EgYvjBp2eAJPr6Kv0lYmDg8ycXksLwvZyJUhqoXriAEAt/A36aI/idFHzh454C4Yy4zhehYmKKHdLvihDZd4x7vWbuj9YG8k0IbHTbMG3n4HF7vYdj7a8qz5vQECUbvLwsE16GHMP8LtPrgAMqCG7x74BaHYmJdmRSEDh/NLHi+InUcrvpdWLRjiREIm5QoJIBUC2ujfspJfeeHLgJzbm6m2kIyH7yltYMwPiLJ28=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
