travis:
  secure:
    BINSTAR_TOKEN: M9t02UtbyRIr0IJGS8hKDiQHwq4dR+1q5zvIfaQ8TPiiYQ3E2ba5kcuDSvwsTl7Apzx/J6OQvbglXOBce/QU40hgcUpuCiMCaZ7Bm8f9943piJfP1sXPAXRJF+MLTTG8xfAJ0rBCHtQ+VfcvB992URoa6p6GA4/laeamlJonHbuSh7l22gz2/yrszbu4C8QEx86iQuVyi4QEigreKE6dTA7WZ0atcaAU0puS7jb5mPriQK4P/tlWgGzzLIgwtHnCzpxUrH6bFVB+ghPrvoWtJG26+S0zKl0U72J3NaXo6EU8NqlS4h4DfLpxVTViq7Z5TU/To9lIjZXd14gSPQ2gBwfiCXOPC81XpjgEyg9Ctae1nLAlEy3k72TLo+vEcwzymGTuyT7/HgpAsRE4VWkVmpAtE/R6/58kp4Gu0Xz0et5jvFNBjXnk9f7nFW8sqJ3bMoV28PtU/D1CA5JdiAigR5ayofOH6+1Dk4a24Kvy1Hquf+Dfxqx7xdcN+N8ef+YFNoIv1aisnd1gwgh2T9tjowbBYHvCC70kGdueispuwNwxYpMWYCQjD57gyZuOcs0idtUVRXgOJA4jrhuprtFZNUagPGpoe3+inDO5KYoa4i5rs4BZ3wPeKPtnJb/MsFHNAoQjIh6dWOyI3j7UhAiCcg1C5Nyjam/gh2dp4uqFGis=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
